---
image:
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdubz/molecule-testing:1.1.0

services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10-dind
    alias: docker

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  ANSIBLE_FORCE_COLOR: "true"

molecule:
  stage: test
  cache:
    key:
      files:
        - .tool-versions
        - tox.ini
    paths:
      - .cache
      - .tox
  before_script:
    - asdf install
  script:
    - tox
