---
image:
  name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/jdubz/molecule-testing:1.1.0

services:
  - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10-dind
    alias: docker

.molecule:
  stage: test
  cache:
    key:
      files:
        - .tool-versions
        - tox.ini
    paths:
      - .tox
      - .cache
  script:
    - asdf list python
    - asdf install
    - tox

debian9:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: debian-stretch
    MOLECULE_IMAGE: debian:stretch-slim

debian10:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: debian-buster
    MOLEDULE_IMAGE: debian:buster-slim

debian11:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: debian-bullseye
    MOLEDULE_IMAGE: debian:bullseye-slim

ubuntu1404:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-trusty
    MOLEDULE_IMAGE: ubuntu:trusty

ubuntu1604:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-xenial
    MOLEDULE_IMAGE: ubuntu:xenial

ubuntu1804:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-bionic
    MOLEDULE_IMAGE: ubuntu:bionic

ubuntu2004:
  extends: .molecule
  variables:
    MOLECULE_PLATFORM: ubuntu-focal
    MOLECULE_IMAGE: ubuntu:focal
