---
- include_tasks: variables.yml
- include_tasks: packages.yml

- name: ensure backup script is in place
  template:
    src: usr/local/bin/daily_backup.j2
    dest: /usr/local/bin/daily_backup
    owner: root
    group: root
    mode: 0755

- name: ensure all backups are configured
  template:
    src: "etc/cron.daily/daily_backup.j2"
    dest: "/etc/cron.daily/daily_backup"
    owner: root
    group: root
    mode: 0755
