---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "${MOLECULE_PLATFORM:-debian-bullseye}"
    image: "jdubz/docker-ci-${MOLECULE_IMAGE:-debian:bullseye-slim}"
    pre_build_image: true
test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - converge
  - idempotence
  - verify
  - destroy
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
