---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: debian-stretch
    image: jdubz/docker-ci-debian:stretch-slim
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-buster
    image: jdubz/docker-ci-debian:buster-slim
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-bullseye
    image: jdubz/docker-ci-debian:bullseye-slim
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-xenial
    image: jdubz/docker-ci-ubuntu:xenial
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-bionic
    image: jdubz/docker-ci-ubuntu:bionic
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-focal
    image: jdubz/docker-ci-ubuntu:focal
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - converge
  - idempotence
  - verify
  - destroy
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
