---
- name: Prepare
  hosts: all
  collections:
    - community.general
  tasks:
    - name: Ensure the locales and tzdata packages are installed
      ansible.builtin.package:
        name:
          - locales
          - tzdata
        update_cache: true
    - name: Ensure the UTF-8 locale is present
      locale_gen:
        name: en_US.UTF-8
        state: present
